### ISSUE TITLE
No .env.example?

### ISSUE THREAD

**Issue by GeorgeBarlow** [BunZe/yaam-client#8]
Couldn't see any example env file of any sort maybe I am being silly. God knows.

**Comment by doyle-mark** [comment]
read the readme..

> When running the development server and when building, YAAM uses an environment variable to direct it to the correct API. Before doing anything, set the REACT_APP_API_ADDR environment variable with the correct address.

**Comment by GeorgeBarlow** [comment]
Sorry was meant to close this yesterday as I had found it.
